// AFMOD — Cars dataset (pure JavaScript)
  // Source: ERLC fandom wiki (Vehicles page) — parsed from MediaWiki API
  // Exposed on the global window object so app.js can use it without ES modules.
  window.CARS = [
  {
    "id": "chevlon-captain-2009",
    "nameEn": "Chevlon Captain 2009",
    "body": "Sedan",
    "bodyAr": "سيدان",
    "class": "Regular",
    "classAr": "عادية",
    "fuel": "Gasoline",
    "fuelAr": "بنزين",
    "price": 118500,
    "topSpeed": "126 MPH",
    "accel": "5.82 seconds",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/4/48/Chevlon_Captain_2009.png",
    "tier": "اقتصادي"
  },
  {
    "id": "vellfire-prima-2009",
    "nameEn": "Vellfire Prima 2009",
    "body": "Sedan",
    "bodyAr": "سيدان",
    "class": "Regular",
    "classAr": "عادية",
    "fuel": "Gasoline",
    "fuelAr": "بنزين",
    "price": 178500,
    "topSpeed": "66 MPH",
    "accel": "4.96 seconds",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/c/c4/Vellfire_Prima_2009.png",
    "tier": "اقتصادي"
  },
  {
    "id": "elysion-slick-2014",
    "nameEn": "Elysion Slick 2014",
    "body": "Sedan",
    "bodyAr": "سيدان",
    "class": "Regular",
    "classAr": "عادية",
    "fuel": "Gasoline",
    "fuelAr": "بنزين",
    "price": 190000,
    "topSpeed": "107 MPH",
    "accel": "5.60 seconds",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/1/11/Elysion_Slick_2014.png",
    "tier": "اقتصادي"
  },
  {
    "id": "navara-imperium-2020",
    "nameEn": "Navara Imperium 2020",
    "body": "Sedan",
    "bodyAr": "سيدان",
    "class": "Regular",
    "classAr": "عادية",
    "fuel": "Gasoline",
    "fuelAr": "بنزين",
    "price": 225000,
    "topSpeed": "110 MPH",
    "accel": "4.87 seconds",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/c/c3/Navara_Imperium_2020.png",
    "tier": "اقتصادي"
  },
  {
    "id": "leland-lts-2010",
    "nameEn": "Leland LTS 2010",
    "body": "Sedan",
    "bodyAr": "سيدان",
    "class": "Regular",
    "classAr": "عادية",
    "fuel": "Gasoline",
    "fuelAr": "بنزين",
    "price": 275000,
    "topSpeed": "122 MPH",
    "accel": "6.30 seconds",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/8/83/Leland_LTS_2010.png",
    "tier": "اقتصادي"
  },
  {
    "id": "sentinel-platinum-1968",
    "nameEn": "Sentinel Platinum 1968",
    "body": "Sedan",
    "bodyAr": "سيدان",
    "class": "Classic",
    "classAr": "كلاسيكية",
    "fuel": "Gasoline",
    "fuelAr": "بنزين",
    "price": 324500,
    "topSpeed": "107 MPH",
    "accel": "5.60 seconds",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/1/19/Sentinel_Platinum_1968.png",
    "tier": "متوسط"
  },
  {
    "id": "chryslus-champion-2005",
    "nameEn": "Chryslus Champion 2005",
    "body": "Sedan",
    "bodyAr": "سيدان",
    "class": "Regular",
    "classAr": "عادية",
    "fuel": "Gasoline",
    "fuelAr": "بنزين",
    "price": 430000,
    "topSpeed": "100 MPH",
    "accel": "5.25 seconds",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/2/20/Chryslus_Champion_2005.png",
    "tier": "متوسط"
  },
  {
    "id": "bullhorn-prancer-2011",
    "nameEn": "Bullhorn Prancer 2011",
    "body": "Sedan",
    "bodyAr": "سيدان",
    "class": "Regular",
    "classAr": "عادية",
    "fuel": "Gasoline",
    "fuelAr": "بنزين",
    "price": 459900,
    "topSpeed": "126 MPH",
    "accel": "5.38 seconds",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/2/24/Bullhorn_Prancer_2011.png",
    "tier": "متوسط"
  },
  {
    "id": "celestial-type-6-2023",
    "nameEn": "Celestial Type-6 2023",
    "body": "Sedan",
    "bodyAr": "سيدان",
    "class": "Electric",
    "classAr": "كهربائية",
    "fuel": "Electric",
    "fuelAr": "كهربائي",
    "price": 467800,
    "topSpeed": "145 MPH",
    "accel": "3.79 seconds",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/9/96/Celestial_Type-6_2023.png",
    "tier": "متوسط"
  },
  {
    "id": "bullhorn-prancer-2015",
    "nameEn": "Bullhorn Prancer 2015",
    "body": "Sedan",
    "bodyAr": "سيدان",
    "class": "Regular",
    "classAr": "عادية",
    "fuel": "Gasoline",
    "fuelAr": "بنزين",
    "price": 485000,
    "topSpeed": "133 MPH",
    "accel": "6.02 seconds",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/5/50/Bullhorn_Prancer_2015.png",
    "tier": "متوسط"
  },
  {
    "id": "bullhorn-prancer-widebody-2020",
    "nameEn": "Bullhorn Prancer Widebody 2020",
    "body": "Sedan",
    "bodyAr": "سيدان",
    "class": "Regular",
    "classAr": "عادية",
    "fuel": "Gasoline",
    "fuelAr": "بنزين",
    "price": 1050000,
    "topSpeed": "136 MPH",
    "accel": "5.12 seconds",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/c/cb/Bullhorn_Prancer_Widebody_2020.png",
    "tier": "فاخر"
  },
  {
    "id": "stuttgart-vierturig-2021",
    "nameEn": "Stuttgart Vierturig 2021",
    "body": "Sedan",
    "bodyAr": "سيدان",
    "class": "Prestige",
    "classAr": "فاخرة",
    "fuel": "Gasoline",
    "fuelAr": "بنزين",
    "price": 1620000,
    "topSpeed": "129 MPH",
    "accel": "5.29 seconds",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/f/ff/Stuttgart_Vierturig_2021.png",
    "tier": "فاخر"
  },
  {
    "id": "averon-rs3-2020",
    "nameEn": "Averon RS3 2020",
    "body": "Sedan",
    "bodyAr": "سيدان",
    "class": "Prestige",
    "classAr": "فاخرة",
    "fuel": "Gasoline",
    "fuelAr": "بنزين",
    "price": 1690000,
    "topSpeed": "120 MPH",
    "accel": "5.12 seconds",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/7/73/Averon_RS3_2020.png",
    "tier": "فاخر"
  },
  {
    "id": "leland-lts5-v-blackwing-2023",
    "nameEn": "Leland LTS5-V Blackwing 2023",
    "body": "Sedan",
    "bodyAr": "سيدان",
    "class": "Prestige",
    "classAr": "فاخرة",
    "fuel": "Gasoline",
    "fuelAr": "بنزين",
    "price": 2550000,
    "topSpeed": "122 MPH",
    "accel": "4.75 seconds",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/9/97/Leland_LTS5-V_Blackwing_2023.png",
    "tier": "فاخر"
  },
  {
    "id": "falcon-coupe-1934",
    "nameEn": "Falcon Coupe 1934",
    "body": "Coupe",
    "bodyAr": "كوبيه",
    "class": "Classic",
    "classAr": "كلاسيكية",
    "fuel": "Gasoline",
    "fuelAr": "بنزين",
    "price": 245000,
    "topSpeed": "119 MPH",
    "accel": "6.26 seconds",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/2/26/Falcon_Coupe_1934.png",
    "tier": "اقتصادي"
  },
  {
    "id": "falcon-coupe-hotrod-1934",
    "nameEn": "Falcon Coupe Hotrod 1934",
    "body": "Coupe",
    "bodyAr": "كوبيه",
    "class": "Classic",
    "classAr": "كلاسيكية",
    "fuel": "Gasoline",
    "fuelAr": "بنزين",
    "price": 289000,
    "topSpeed": "121 MPH",
    "accel": "5.18 seconds",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/8/8a/Falcon_Coupe_Hotrod_1934.png",
    "tier": "اقتصادي"
  },
  {
    "id": "chevlon-corbeta-c2-1967",
    "nameEn": "Chevlon Corbeta C2 1967",
    "body": "Coupe",
    "bodyAr": "كوبيه",
    "class": "Classic",
    "classAr": "كلاسيكية",
    "fuel": "Gasoline",
    "fuelAr": "بنزين",
    "price": 290000,
    "topSpeed": "140 MPH",
    "accel": "6.80 seconds",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/2/28/Chevlon_Corbeta_C2_1967.png",
    "tier": "اقتصادي"
  },
  {
    "id": "vellfire-runabout-1984",
    "nameEn": "Vellfire Runabout 1984",
    "body": "Coupe",
    "bodyAr": "كوبيه",
    "class": "Classic",
    "classAr": "كلاسيكية",
    "fuel": "Gasoline",
    "fuelAr": "بنزين",
    "price": 390000,
    "topSpeed": "107 MPH",
    "accel": "5.07 seconds",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/2/29/Vellfire_Runabout_1984.png",
    "tier": "متوسط"
  },
  {
    "id": "arrow-phoenix-nationals-1977",
    "nameEn": "Arrow Phoenix Nationals 1977",
    "body": "Coupe",
    "bodyAr": "كوبيه",
    "class": "Classic",
    "classAr": "كلاسيكية",
    "fuel": "Gasoline",
    "fuelAr": "بنزين",
    "price": 470000,
    "topSpeed": "123 MPH",
    "accel": "6.93 seconds",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/6/63/Arrow_Phoenix_Nationals_1977.png",
    "tier": "متوسط"
  },
  {
    "id": "bullhorn-prancer-1969",
    "nameEn": "Bullhorn Prancer 1969",
    "body": "Coupe",
    "bodyAr": "كوبيه",
    "class": "Classic",
    "classAr": "كلاسيكية",
    "fuel": "Gasoline",
    "fuelAr": "بنزين",
    "price": 485000,
    "topSpeed": "112 MPH",
    "accel": "5.04 seconds",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/5/59/Bullhorn_Prancer_1969.png",
    "tier": "متوسط"
  },
  {
    "id": "bullhorn-determinator-2008",
    "nameEn": "Bullhorn Determinator 2008",
    "body": "Coupe",
    "bodyAr": "كوبيه",
    "class": "Regular",
    "classAr": "عادية",
    "fuel": "Gasoline",
    "fuelAr": "بنزين",
    "price": 490000,
    "topSpeed": "125 MPH",
    "accel": "5.42 seconds",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/b/ba/Bullhorn_Determinator_2008.png",
    "tier": "متوسط"
  },
  {
    "id": "falcon-stallion-350-1969",
    "nameEn": "Falcon Stallion 350 1969",
    "body": "Coupe",
    "bodyAr": "كوبيه",
    "class": "Classic",
    "classAr": "كلاسيكية",
    "fuel": "Gasoline",
    "fuelAr": "بنزين",
    "price": 506660,
    "topSpeed": "114 MPH",
    "accel": "4.90 seconds",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/8/85/Falcon_Stallion_350_1969.png",
    "tier": "متوسط"
  },
  {
    "id": "chevlon-amigo-sport-2016",
    "nameEn": "Chevlon Amigo Sport 2016",
    "body": "Coupe",
    "bodyAr": "كوبيه",
    "class": "Regular",
    "classAr": "عادية",
    "fuel": "Gasoline",
    "fuelAr": "بنزين",
    "price": 552500,
    "topSpeed": "129 MPH",
    "accel": "6.06 seconds",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/f/f0/Chevlon_Amigo_Sport_2016.png",
    "tier": "متوسط"
  },
  {
    "id": "chevlon-amigo-lzr-2011",
    "nameEn": "Chevlon Amigo LZR 2011",
    "body": "Coupe",
    "bodyAr": "كوبيه",
    "class": "Regular",
    "classAr": "عادية",
    "fuel": "Gasoline",
    "fuelAr": "بنزين",
    "price": 585000,
    "topSpeed": "133 MPH",
    "accel": "4.51 seconds",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/f/f4/Chevlon_Amigo_LZR_2011_main.png",
    "tier": "متوسط"
  },
  {
    "id": "chevlon-corbeta-x08-2014",
    "nameEn": "Chevlon Corbeta X08 2014",
    "body": "Coupe",
    "bodyAr": "كوبيه",
    "class": "Prestige",
    "classAr": "فاخرة",
    "fuel": "Gasoline",
    "fuelAr": "بنزين",
    "price": 960000,
    "topSpeed": "153 MPH",
    "accel": "4.56 seconds",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/f/f8/Chevlon_Corbeta_X08_2014.png",
    "tier": "فاخر"
  },
  {
    "id": "bullhorn-determinator-sfp-fury-2022",
    "nameEn": "Bullhorn Determinator SFP Fury 2022",
    "body": "Coupe",
    "bodyAr": "كوبيه",
    "class": "Regular",
    "classAr": "عادية",
    "fuel": "Gasoline",
    "fuelAr": "بنزين",
    "price": 995000,
    "topSpeed": "162 MPH",
    "accel": "4.54 seconds",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/1/1b/Bullhorn_Determinator_SFP_Fury_2022.png",
    "tier": "فاخر"
  },
  {
    "id": "bullhorn-determinator-sfp-blackjack-widebody-2022",
    "nameEn": "Bullhorn Determinator SFP Blackjack Widebody 2022",
    "body": "Coupe",
    "bodyAr": "كوبيه",
    "class": "Regular",
    "classAr": "عادية",
    "fuel": "Gasoline",
    "fuelAr": "بنزين",
    "price": 1249990,
    "topSpeed": "162 MPH",
    "accel": "4.19 seconds",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/f/f1/Bullhorn_Determinator_SFP_Blackjack_Widebody_2022.png",
    "tier": "فاخر"
  },
  {
    "id": "averon-s5-2010",
    "nameEn": "Averon S5 2010",
    "body": "Coupe",
    "bodyAr": "كوبيه",
    "class": "Prestige",
    "classAr": "فاخرة",
    "fuel": "Gasoline",
    "fuelAr": "بنزين",
    "price": 1327950,
    "topSpeed": "117 MPH",
    "accel": "4.86 seconds",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/0/08/Averon_S5_2010.png",
    "tier": "فاخر"
  },
  {
    "id": "falcon-stallion-350-2015",
    "nameEn": "Falcon Stallion 350 2015",
    "body": "Coupe",
    "bodyAr": "كوبيه",
    "class": "Regular",
    "classAr": "عادية",
    "fuel": "Gasoline",
    "fuelAr": "بنزين",
    "price": 1390000,
    "topSpeed": "125 MPH",
    "accel": "4.81 seconds",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/c/c1/Falcon_Stallion_350_2015.png",
    "tier": "فاخر"
  },
  {
    "id": "bkm-risen-roadster-2020",
    "nameEn": "BKM Risen Roadster 2020",
    "body": "Coupe",
    "bodyAr": "كوبيه",
    "class": "Electric",
    "classAr": "كهربائية",
    "fuel": "Electric",
    "fuelAr": "كهربائي",
    "price": 1642950,
    "topSpeed": "146 MPH",
    "accel": "3.93 seconds",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/e/e7/BKM_Risen_Roadster_2020.png",
    "tier": "فاخر"
  },
  {
    "id": "navara-horizon-2013",
    "nameEn": "Navara Horizon 2013",
    "body": "Coupe",
    "bodyAr": "كوبيه",
    "class": "Regular",
    "classAr": "عادية",
    "fuel": "Gasoline",
    "fuelAr": "بنزين",
    "price": 1985000,
    "topSpeed": "157 MPH",
    "accel": "3.86 seconds",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/7/79/Navara_Horizon_2013.png",
    "tier": "فاخر"
  },
  {
    "id": "vellfire-pioneer-2019",
    "nameEn": "Vellfire Pioneer 2019",
    "body": "Coupe",
    "bodyAr": "كوبيه",
    "class": "Regular",
    "classAr": "عادية",
    "fuel": "Gasoline",
    "fuelAr": "بنزين",
    "price": 1998200,
    "topSpeed": "128 MPH",
    "accel": "5.95 seconds",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/7/7f/Vellfire_Pioneer_2019.png",
    "tier": "فاخر"
  },
  {
    "id": "chevlon-corbeta-tz-2014",
    "nameEn": "Chevlon Corbeta TZ 2014",
    "body": "Coupe",
    "bodyAr": "كوبيه",
    "class": "Prestige",
    "classAr": "فاخرة",
    "fuel": "Gasoline",
    "fuelAr": "بنزين",
    "price": 3500000,
    "topSpeed": "163 MPH",
    "accel": "4.14 seconds",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/c/cb/Chevlon_Corbeta_TZ_2014.png",
    "tier": "حصري"
  },
  {
    "id": "chevlon-corbeta-8-2023",
    "nameEn": "Chevlon Corbeta 8 2023",
    "body": "Coupe",
    "bodyAr": "كوبيه",
    "class": "Prestige",
    "classAr": "فاخرة",
    "fuel": "Gasoline",
    "fuelAr": "بنزين",
    "price": 4100000,
    "topSpeed": "157 MPH",
    "accel": "3.96 seconds",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/9/9f/Chevlon_Corbeta_8_2023.png",
    "tier": "حصري"
  },
  {
    "id": "takeo-experience-2021",
    "nameEn": "Takeo Experience 2021",
    "body": "Coupe",
    "bodyAr": "كوبيه",
    "class": "Prestige",
    "classAr": "فاخرة",
    "fuel": "Gasoline",
    "fuelAr": "بنزين",
    "price": 4750000,
    "topSpeed": "140 MPH",
    "accel": "3.27 seconds",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/5/54/Takeo_Experience_2021.png",
    "tier": "حصري"
  },
  {
    "id": "falcon-heritage-2021",
    "nameEn": "Falcon Heritage 2021",
    "body": "Coupe",
    "bodyAr": "كوبيه",
    "class": "Prestige",
    "classAr": "فاخرة",
    "fuel": "Gasoline",
    "fuelAr": "بنزين",
    "price": 6209000,
    "topSpeed": "167 MPH",
    "accel": "3.25 seconds",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/3/37/Screenshot_2025-08-03_080041.png",
    "tier": "حصري"
  },
  {
    "id": "averon-r8-2017",
    "nameEn": "Averon R8 2017",
    "body": "Coupe",
    "bodyAr": "كوبيه",
    "class": "Prestige",
    "classAr": "فاخرة",
    "fuel": "Gasoline",
    "fuelAr": "بنزين",
    "price": 6500000,
    "topSpeed": "146 MPH",
    "accel": "4.97 seconds",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/b/b5/Averon_R8_2017.png",
    "tier": "حصري"
  },
  {
    "id": "surrey-650s-2016",
    "nameEn": "Surrey 650S 2016",
    "body": "Coupe",
    "bodyAr": "كوبيه",
    "class": "Prestige",
    "classAr": "فاخرة",
    "fuel": "Gasoline",
    "fuelAr": "بنزين",
    "price": 8900000,
    "topSpeed": "150 MPH",
    "accel": "3.74 seconds",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/2/28/Surrey_650S_2016.png",
    "tier": "حصري"
  },
  {
    "id": "strugatti-ettore-2020",
    "nameEn": "Strugatti Ettore 2020",
    "body": "Coupe",
    "bodyAr": "كوبيه",
    "class": "Prestige",
    "classAr": "فاخرة",
    "fuel": "Gasoline",
    "fuelAr": "بنزين",
    "price": 15000000,
    "topSpeed": "170 MPH",
    "accel": "3.88 seconds",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/8/82/Strugatti_Ettore_2020.png",
    "tier": "حصري"
  },
  {
    "id": "chevlon-camion-2002",
    "nameEn": "Chevlon Camion 2002",
    "body": "SUV",
    "bodyAr": "دفع رباعي",
    "class": "Regular",
    "classAr": "عادية",
    "fuel": "Gasoline",
    "fuelAr": "بنزين",
    "price": 89000,
    "topSpeed": "98 MPH",
    "accel": "8.40 seconds",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/9/90/Chevlon_Camion_2002.png",
    "tier": "اقتصادي"
  },
  {
    "id": "overland-apache-1995",
    "nameEn": "Overland Apache 1995",
    "body": "SUV",
    "bodyAr": "دفع رباعي",
    "class": "Regular",
    "classAr": "عادية",
    "fuel": "Gasoline",
    "fuelAr": "بنزين",
    "price": 99500,
    "topSpeed": "110 MPH",
    "accel": "9.20 seconds",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/2/29/Overland_Apache_1995.png",
    "tier": "اقتصادي"
  },
  {
    "id": "falcon-traveller-2003",
    "nameEn": "Falcon Traveller 2003",
    "body": "SUV",
    "bodyAr": "دفع رباعي",
    "class": "Regular",
    "classAr": "عادية",
    "fuel": "Gasoline",
    "fuelAr": "بنزين",
    "price": 125000,
    "topSpeed": "128 MPH",
    "accel": "7.60 seconds",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/6/6c/Falcon_Traveller_2003.png",
    "tier": "اقتصادي"
  },
  {
    "id": "falcon-scavenger-security-2013",
    "nameEn": "Falcon Scavenger Security 2013",
    "body": "SUV",
    "bodyAr": "دفع رباعي",
    "class": "Commercial",
    "classAr": "تجارية",
    "fuel": "Gasoline",
    "fuelAr": "بنزين",
    "price": 150000,
    "topSpeed": "124 MPH",
    "accel": "N/A",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/7/7d/Falcon_Scavenger_Security_2013.png",
    "tier": "اقتصادي"
  },
  {
    "id": "chevlon-camion-2008",
    "nameEn": "Chevlon Camion 2008",
    "body": "SUV",
    "bodyAr": "دفع رباعي",
    "class": "Regular",
    "classAr": "عادية",
    "fuel": "Gasoline",
    "fuelAr": "بنزين",
    "price": 280500,
    "topSpeed": "126 MPH",
    "accel": "7.17 seconds",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/f/fd/Chevlon_Camion_2008.png",
    "tier": "اقتصادي"
  },
  {
    "id": "chevlon-camion-2018",
    "nameEn": "Chevlon Camion 2018",
    "body": "SUV",
    "bodyAr": "دفع رباعي",
    "class": "Regular",
    "classAr": "عادية",
    "fuel": "Gasoline",
    "fuelAr": "بنزين",
    "price": 345000,
    "topSpeed": "131 MPH",
    "accel": "7.18 seconds",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/f/fe/Chevlon_Camion_2018.png",
    "tier": "متوسط"
  },
  {
    "id": "falcon-scavenger-2016",
    "nameEn": "Falcon Scavenger 2016",
    "body": "SUV",
    "bodyAr": "دفع رباعي",
    "class": "Regular",
    "classAr": "عادية",
    "fuel": "Gasoline",
    "fuelAr": "بنزين",
    "price": 397000,
    "topSpeed": "127 MPH",
    "accel": "6.70 seconds",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/4/4a/Falcon_Scavenger_2016.png",
    "tier": "متوسط"
  },
  {
    "id": "chevlon-revver-2005",
    "nameEn": "Chevlon Revver 2005",
    "body": "SUV",
    "bodyAr": "دفع رباعي",
    "class": "Regular",
    "classAr": "عادية",
    "fuel": "Gasoline",
    "fuelAr": "بنزين",
    "price": 400000,
    "topSpeed": "132 MPH",
    "accel": "7.65 seconds",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/7/7a/Chevlon_Revver_2005.png",
    "tier": "متوسط"
  },
  {
    "id": "overland-apache-2011",
    "nameEn": "Overland Apache 2011",
    "body": "SUV",
    "bodyAr": "دفع رباعي",
    "class": "Regular",
    "classAr": "عادية",
    "fuel": "Gasoline",
    "fuelAr": "بنزين",
    "price": 420000,
    "topSpeed": "128 MPH",
    "accel": "6.48 seconds",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/7/71/Overland_Apache_2011.png",
    "tier": "متوسط"
  },
  {
    "id": "overland-buckaroo-2018",
    "nameEn": "Overland Buckaroo 2018",
    "body": "SUV",
    "bodyAr": "دفع رباعي",
    "class": "Regular",
    "classAr": "عادية",
    "fuel": "Gasoline",
    "fuelAr": "بنزين",
    "price": 427000,
    "topSpeed": "131 MPH",
    "accel": "7.73 seconds",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/4/4f/Overland_Buckaroo_2018.png",
    "tier": "متوسط"
  },
  {
    "id": "vellfire-riptide-2020",
    "nameEn": "Vellfire Riptide 2020",
    "body": "SUV",
    "bodyAr": "دفع رباعي",
    "class": "Regular",
    "classAr": "عادية",
    "fuel": "Gasoline",
    "fuelAr": "بنزين",
    "price": 452000,
    "topSpeed": "136 MPH",
    "accel": "7.15 seconds",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/f/f9/Vellfire_Riptide_2020.png",
    "tier": "متوسط"
  },
  {
    "id": "chevlon-camion-2021",
    "nameEn": "Chevlon Camion 2021",
    "body": "SUV",
    "bodyAr": "دفع رباعي",
    "class": "Regular",
    "classAr": "عادية",
    "fuel": "Gasoline",
    "fuelAr": "بنزين",
    "price": 495000,
    "topSpeed": "128 MPH",
    "accel": "5.82 seconds",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/4/44/Chevlon_Camion_2021.png",
    "tier": "متوسط"
  },
  {
    "id": "falcon-estallion-2024",
    "nameEn": "Falcon eStallion 2024",
    "body": "SUV",
    "bodyAr": "دفع رباعي",
    "class": "Electric",
    "classAr": "كهربائية",
    "fuel": "Electric",
    "fuelAr": "كهربائي",
    "price": 510000,
    "topSpeed": "124 MPH",
    "accel": "3.83 seconds",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/e/e2/Falcon_eStallion_2024.png",
    "tier": "متوسط"
  },
  {
    "id": "falcon-rampage-bigfoot-2-door-2021",
    "nameEn": "Falcon Rampage Bigfoot 2-Door 2021",
    "body": "SUV",
    "bodyAr": "دفع رباعي",
    "class": "Regular",
    "classAr": "عادية",
    "fuel": "Gasoline",
    "fuelAr": "بنزين",
    "price": 650000,
    "topSpeed": "99 MPH",
    "accel": "5.39 seconds",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/0/0b/Falcon_Rampage_Bigfoot_2-Door_2021.png",
    "tier": "متوسط"
  },
  {
    "id": "averon-anodic-2024",
    "nameEn": "Averon Anodic 2024",
    "body": "SUV",
    "bodyAr": "دفع رباعي",
    "class": "Electric",
    "classAr": "كهربائية",
    "fuel": "Electric",
    "fuelAr": "كهربائي",
    "price": 699900,
    "topSpeed": "119 MPH",
    "accel": "5.75 seconds",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/9/9d/Averon_Anodic_2024.png",
    "tier": "متوسط"
  },
  {
    "id": "bullhorn-pueblo-2018",
    "nameEn": "Bullhorn Pueblo 2018",
    "body": "SUV",
    "bodyAr": "دفع رباعي",
    "class": "Regular",
    "classAr": "عادية",
    "fuel": "Gasoline",
    "fuelAr": "بنزين",
    "price": 795000,
    "topSpeed": "125 MPH",
    "accel": "5.62 seconds",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/b/be/Bullhorn_Pueblo_2018.png",
    "tier": "متوسط"
  },
  {
    "id": "overland-apache-sfp-2020",
    "nameEn": "Overland Apache SFP 2020",
    "body": "SUV",
    "bodyAr": "دفع رباعي",
    "class": "Regular",
    "classAr": "عادية",
    "fuel": "Gasoline",
    "fuelAr": "بنزين",
    "price": 920000,
    "topSpeed": "147 MPH",
    "accel": "4.67 seconds",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/f/f8/Overland_Apache_SFP_2020.png",
    "tier": "فاخر"
  },
  {
    "id": "leland-vault-2020",
    "nameEn": "Leland Vault 2020",
    "body": "SUV",
    "bodyAr": "دفع رباعي",
    "class": "Prestige",
    "classAr": "فاخرة",
    "fuel": "Gasoline",
    "fuelAr": "بنزين",
    "price": 1249000,
    "topSpeed": "125 MPH",
    "accel": "5.49 seconds",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/f/f2/Leland_Vault_2020.png",
    "tier": "فاخر"
  },
  {
    "id": "falcon-rampage-beast-2021",
    "nameEn": "Falcon Rampage Beast 2021",
    "body": "SUV",
    "bodyAr": "دفع رباعي",
    "class": "Regular",
    "classAr": "عادية",
    "fuel": "Gasoline",
    "fuelAr": "بنزين",
    "price": 1295000,
    "topSpeed": "99 MPH",
    "accel": "5.85 seconds",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/0/0f/Falcon_Rampage_Beast_2021.png",
    "tier": "فاخر"
  },
  {
    "id": "ferdinand-jalapeno-turbo-2022",
    "nameEn": "Ferdinand Jalapeno Turbo 2022",
    "body": "SUV",
    "bodyAr": "دفع رباعي",
    "class": "Prestige",
    "classAr": "فاخرة",
    "fuel": "Gasoline",
    "fuelAr": "بنزين",
    "price": 1450000,
    "topSpeed": "155 MPH",
    "accel": "5.16 seconds",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/e/ea/Ferdinand_Jalapeno_Turbo_2022.png",
    "tier": "فاخر"
  },
  {
    "id": "bkm-munich-2020",
    "nameEn": "BKM Munich 2020",
    "body": "SUV",
    "bodyAr": "دفع رباعي",
    "class": "Prestige",
    "classAr": "فاخرة",
    "fuel": "Gasoline",
    "fuelAr": "بنزين",
    "price": 1560000,
    "topSpeed": "125 MPH",
    "accel": "5.42 seconds",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/b/b2/BKM_Munich_2020.png",
    "tier": "فاخر"
  },
  {
    "id": "terrain-traveller-2022",
    "nameEn": "Terrain Traveller 2022",
    "body": "SUV",
    "bodyAr": "دفع رباعي",
    "class": "Prestige",
    "classAr": "فاخرة",
    "fuel": "Gasoline",
    "fuelAr": "بنزين",
    "price": 1590000,
    "topSpeed": "129 MPH",
    "accel": "5.42 seconds",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/9/9b/Terrain_Traveller_2022.png",
    "tier": "فاخر"
  },
  {
    "id": "averon-q8-2022",
    "nameEn": "Averon Q8 2022",
    "body": "SUV",
    "bodyAr": "دفع رباعي",
    "class": "Prestige",
    "classAr": "فاخرة",
    "fuel": "Gasoline",
    "fuelAr": "بنزين",
    "price": 1900000,
    "topSpeed": "125 MPH",
    "accel": "5.41 seconds",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/c/cd/Averon_Q8_2022.png",
    "tier": "فاخر"
  },
  {
    "id": "stuttgart-landschaft-2022",
    "nameEn": "Stuttgart Landschaft 2022",
    "body": "SUV",
    "bodyAr": "دفع رباعي",
    "class": "Regular",
    "classAr": "عادية",
    "fuel": "Gasoline",
    "fuelAr": "بنزين",
    "price": 2490000,
    "topSpeed": "124 MPH",
    "accel": "5.67 seconds",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/3/38/Stuttgart_Landschaft_2022.png",
    "tier": "فاخر"
  },
  {
    "id": "vellfire-evertt-1995",
    "nameEn": "Vellfire Evertt 1995",
    "body": "Truck",
    "bodyAr": "شاحنة",
    "class": "Regular",
    "classAr": "عادية",
    "fuel": "Gasoline",
    "fuelAr": "بنزين",
    "price": 145000,
    "topSpeed": "124 MPH",
    "accel": "7.17 seconds",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/5/5b/Vellfire_Evertt_1995.png",
    "tier": "اقتصادي"
  },
  {
    "id": "chevlon-l-15-1981",
    "nameEn": "Chevlon L/15 1981",
    "body": "Truck",
    "bodyAr": "شاحنة",
    "class": "Classic",
    "classAr": "كلاسيكية",
    "fuel": "Gasoline",
    "fuelAr": "بنزين",
    "price": 167000,
    "topSpeed": "121 MPH",
    "accel": "6.58 seconds",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/e/e7/Chevlon_L-15_1981.png",
    "tier": "اقتصادي"
  },
  {
    "id": "mail-truck",
    "nameEn": "Mail Truck",
    "body": "Truck",
    "bodyAr": "شاحنة",
    "class": "Commercial",
    "classAr": "تجارية",
    "fuel": "Gasoline",
    "fuelAr": "بنزين",
    "price": 180000,
    "topSpeed": "87 MPH",
    "accel": "19.73 seconds",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/1/16/Mail_Truck.png",
    "tier": "اقتصادي"
  },
  {
    "id": "chevlon-landslide-2007",
    "nameEn": "Chevlon Landslide 2007",
    "body": "Truck",
    "bodyAr": "شاحنة",
    "class": "Regular",
    "classAr": "عادية",
    "fuel": "Gasoline",
    "fuelAr": "بنزين",
    "price": 195000,
    "topSpeed": "128 MPH",
    "accel": "7.99 seconds",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/8/82/Chevlon_Landslide_2007.png",
    "tier": "اقتصادي"
  },
  {
    "id": "chevlon-inferno-1981",
    "nameEn": "Chevlon Inferno 1981",
    "body": "Truck",
    "bodyAr": "شاحنة",
    "class": "Classic",
    "classAr": "كلاسيكية",
    "fuel": "Gasoline",
    "fuelAr": "بنزين",
    "price": 199750,
    "topSpeed": "135 MPH",
    "accel": "8.17 seconds",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/6/67/Chevlon_Inferno_1981.png",
    "tier": "اقتصادي"
  },
  {
    "id": "chevlon-l-35-extended-1981",
    "nameEn": "Chevlon L/35 Extended 1981",
    "body": "Truck",
    "bodyAr": "شاحنة",
    "class": "Classic",
    "classAr": "كلاسيكية",
    "fuel": "Gasoline",
    "fuelAr": "بنزين",
    "price": 249000,
    "topSpeed": "121 MPH",
    "accel": "6.68 seconds",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/2/24/Chevlon_L-35_Extended_1981.png",
    "tier": "اقتصادي"
  },
  {
    "id": "bullhorn-bh15-2009",
    "nameEn": "Bullhorn BH15 2009",
    "body": "Truck",
    "bodyAr": "شاحنة",
    "class": "Regular",
    "classAr": "عادية",
    "fuel": "Gasoline",
    "fuelAr": "بنزين",
    "price": 305000,
    "topSpeed": "127 MPH",
    "accel": "7.19 seconds",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/c/ca/Bullhorn_BH15_2009.png",
    "tier": "متوسط"
  },
  {
    "id": "navara-boundary-2022",
    "nameEn": "Navara Boundary 2022",
    "body": "Truck",
    "bodyAr": "شاحنة",
    "class": "Regular",
    "classAr": "عادية",
    "fuel": "Gasoline",
    "fuelAr": "بنزين",
    "price": 459900,
    "topSpeed": "140 MPH",
    "accel": "7.47 seconds",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/0/05/Navara_Boundary_2022.png",
    "tier": "متوسط"
  },
  {
    "id": "bank-truck",
    "nameEn": "Bank Truck",
    "body": "Truck",
    "bodyAr": "شاحنة",
    "class": "Commercial",
    "classAr": "تجارية",
    "fuel": "Diesel",
    "fuelAr": "ديزل",
    "price": 470000,
    "topSpeed": "82 MPH",
    "accel": "N/A",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/4/45/Bank_Truck.png",
    "tier": "متوسط"
  },
  {
    "id": "chevlon-platoro-2019",
    "nameEn": "Chevlon Platoro 2019",
    "body": "Truck",
    "bodyAr": "شاحنة",
    "class": "Regular",
    "classAr": "عادية",
    "fuel": "Gasoline",
    "fuelAr": "بنزين",
    "price": 590000,
    "topSpeed": "131 MPH",
    "accel": "7.43 seconds",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/1/11/Chevlon_Platoro_2019.png",
    "tier": "متوسط"
  },
  {
    "id": "three-guys-food-truck",
    "nameEn": "Three Guys Food Truck",
    "body": "Truck",
    "bodyAr": "شاحنة",
    "class": "Commercial",
    "classAr": "تجارية",
    "fuel": "Gasoline or Diesel",
    "fuelAr": "Gasoline or Diesel",
    "price": 599000,
    "topSpeed": "97 MPH",
    "accel": "N/A",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/9/93/Three_Guys_Food_Truck.png",
    "tier": "متوسط"
  },
  {
    "id": "la-mesa-food-truck",
    "nameEn": "La Mesa Food Truck",
    "body": "Truck",
    "bodyAr": "شاحنة",
    "class": "Commercial",
    "classAr": "تجارية",
    "fuel": "Gasoline or Diesel",
    "fuelAr": "Gasoline or Diesel",
    "price": 599000,
    "topSpeed": "97 MPH",
    "accel": "N/A",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/6/6c/La_Mesa_Food_Truck.png",
    "tier": "متوسط"
  },
  {
    "id": "vellfire-prairie-2022",
    "nameEn": "Vellfire Prairie 2022",
    "body": "Truck",
    "bodyAr": "شاحنة",
    "class": "Regular",
    "classAr": "عادية",
    "fuel": "Gasoline",
    "fuelAr": "بنزين",
    "price": 600000,
    "topSpeed": "131 MPH",
    "accel": "7.51 seconds",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/4/4c/Vellfire_Prairie_2022.png",
    "tier": "متوسط"
  },
  {
    "id": "celestial-truckatron-2024",
    "nameEn": "Celestial Truckatron 2024",
    "body": "Truck",
    "bodyAr": "شاحنة",
    "class": "Electric",
    "classAr": "كهربائية",
    "fuel": "Electric",
    "fuelAr": "كهربائي",
    "price": 1799500,
    "topSpeed": "122 MPH",
    "accel": "3.66 seconds",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/1/17/Celestial_Truckatron_2024.png",
    "tier": "فاخر"
  },
  {
    "id": "chevlon-commuter-van-2006",
    "nameEn": "Chevlon Commuter Van 2006",
    "body": "Industrial",
    "bodyAr": "صناعية",
    "class": "Regular",
    "classAr": "عادية",
    "fuel": "Gasoline",
    "fuelAr": "بنزين",
    "price": 250000,
    "topSpeed": "84 MPH",
    "accel": "6.33 seconds",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/d/d8/Chevlon_Commuter_Van_2006.png",
    "tier": "اقتصادي"
  },
  {
    "id": "chevlon-news-van-2006",
    "nameEn": "Chevlon News Van 2006",
    "body": "Industrial",
    "bodyAr": "صناعية",
    "class": "Commercial",
    "classAr": "تجارية",
    "fuel": "Gasoline",
    "fuelAr": "بنزين",
    "price": 310000,
    "topSpeed": "84 MPH",
    "accel": "N/A",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/a/ae/Chevlon_News_Van_2006.png",
    "tier": "متوسط"
  },
  {
    "id": "farm-tractor-5100m",
    "nameEn": "Farm Tractor 5100M",
    "body": "Industrial",
    "bodyAr": "صناعية",
    "class": "Utility",
    "classAr": "خدمية",
    "fuel": "Diesel",
    "fuelAr": "ديزل",
    "price": 350000,
    "topSpeed": "46 MPH",
    "accel": "N/A",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/9/99/Farm_Tractor_5100M.png",
    "tier": "متوسط"
  },
  {
    "id": "garbage-truck",
    "nameEn": "Garbage Truck",
    "body": "Industrial",
    "bodyAr": "صناعية",
    "class": "Commercial",
    "classAr": "تجارية",
    "fuel": "Diesel",
    "fuelAr": "ديزل",
    "price": 479000,
    "topSpeed": "80 MPH",
    "accel": "N/A",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/9/93/Garbage_Truck.png",
    "tier": "متوسط"
  },
  {
    "id": "fuel-tanker",
    "nameEn": "Fuel Tanker",
    "body": "Industrial",
    "bodyAr": "صناعية",
    "class": "Commercial",
    "classAr": "تجارية",
    "fuel": "Diesel",
    "fuelAr": "ديزل",
    "price": 550000,
    "topSpeed": "80 MPH",
    "accel": "N/A",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/c/cc/Fuel_Tanker.png",
    "tier": "متوسط"
  },
  {
    "id": "mail-van",
    "nameEn": "Mail Van",
    "body": "Industrial",
    "bodyAr": "صناعية",
    "class": "Commercial",
    "classAr": "تجارية",
    "fuel": "Gasoline or Diesel",
    "fuelAr": "Gasoline or Diesel",
    "price": 650000,
    "topSpeed": "97 MPH",
    "accel": "5.58 seconds",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/0/0d/Mail_Van.png",
    "tier": "متوسط"
  },
  {
    "id": "front-loader-tractor",
    "nameEn": "Front Loader Tractor",
    "body": "Industrial",
    "bodyAr": "صناعية",
    "class": "Commercial",
    "classAr": "تجارية",
    "fuel": "Diesel",
    "fuelAr": "ديزل",
    "price": 650000,
    "topSpeed": "73 MPH",
    "accel": "N/A",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/1/17/Front_Loader_Tractor.png",
    "tier": "متوسط"
  },
  {
    "id": "dump-truck",
    "nameEn": "Dump Truck",
    "body": "Industrial",
    "bodyAr": "صناعية",
    "class": "Commercial",
    "classAr": "تجارية",
    "fuel": "Diesel",
    "fuelAr": "ديزل",
    "price": 650000,
    "topSpeed": "156 MPH",
    "accel": "N/A",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/3/33/Dump_truck.png",
    "tier": "متوسط"
  },
  {
    "id": "forklift",
    "nameEn": "Forklift",
    "body": "Industrial",
    "bodyAr": "صناعية",
    "class": "Commercial",
    "classAr": "تجارية",
    "fuel": "Diesel",
    "fuelAr": "ديزل",
    "price": 650000,
    "topSpeed": "53 MPH",
    "accel": "N/A",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/9/94/Forklift_Main.png",
    "tier": "متوسط"
  },
  {
    "id": "front-loader-garbage-truck",
    "nameEn": "Front-Loader Garbage Truck",
    "body": "Industrial",
    "bodyAr": "صناعية",
    "class": "Commercial",
    "classAr": "تجارية",
    "fuel": "Diesel",
    "fuelAr": "ديزل",
    "price": 790000,
    "topSpeed": "80 MPH",
    "accel": "N/A",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/0/0c/Garbagetr.png",
    "tier": "متوسط"
  },
  {
    "id": "shuttle-bus",
    "nameEn": "Shuttle Bus",
    "body": "Industrial",
    "bodyAr": "صناعية",
    "class": "Commercial",
    "classAr": "تجارية",
    "fuel": "Gasoline",
    "fuelAr": "بنزين",
    "price": 870000,
    "topSpeed": "90 MPH",
    "accel": "N/A",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/d/d6/Shuttle_Bus.png",
    "tier": "فاخر"
  },
  {
    "id": "metro-transit-bus",
    "nameEn": "Metro Transit Bus",
    "body": "Bus",
    "bodyAr": "حافلة",
    "class": "Commercial",
    "classAr": "تجارية",
    "fuel": "Gasoline (Hybrid IRL)",
    "fuelAr": "Gasoline (Hybrid IRL)",
    "price": 3940000,
    "topSpeed": "94 MPH",
    "accel": "N/A",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/7/7b/Metro_Transit_Bus_main.png",
    "tier": "حصري"
  },
  {
    "id": "lawn-mower",
    "nameEn": "Lawn Mower",
    "body": "ATV",
    "bodyAr": "رباعية",
    "class": "Regular",
    "classAr": "عادية",
    "fuel": "Gasoline",
    "fuelAr": "بنزين",
    "price": 29000,
    "topSpeed": "11 MPH",
    "accel": "N/A",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/1/1f/Lawn_Mower.png",
    "tier": "اقتصادي"
  },
  {
    "id": "4-wheeler",
    "nameEn": "4-Wheeler",
    "body": "ATV",
    "bodyAr": "رباعية",
    "class": "Regular",
    "classAr": "عادية",
    "fuel": "Gasoline",
    "fuelAr": "بنزين",
    "price": 135000,
    "topSpeed": "60 MPH",
    "accel": "4.73 seconds",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/a/a8/4-Wheeler_main.png",
    "tier": "اقتصادي"
  },
  {
    "id": "falcon-scavenger-taxi-2020",
    "nameEn": "Falcon Scavenger Taxi 2020",
    "body": "Car",
    "bodyAr": "سيارة",
    "class": "SUV",
    "classAr": "دفع رباعي",
    "fuel": "Gasoline",
    "fuelAr": "بنزين",
    "price": 190000,
    "topSpeed": "128 MPH",
    "accel": "N/A",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/7/7c/Falcon_Scavenger_Taxi_2020.png",
    "tier": "اقتصادي"
  },
  {
    "id": "leland-limo-2018",
    "nameEn": "Leland Limo 2018",
    "body": "Car",
    "bodyAr": "سيارة",
    "class": "Commercial",
    "classAr": "تجارية",
    "fuel": "Gasoline",
    "fuelAr": "بنزين",
    "price": 950000,
    "topSpeed": "154 MPH",
    "accel": "N/A",
    "image": "https://static.wikia.nocookie.net/emergency-response-liberty-county/images/d/d1/Leland_Limo_2018.png",
    "tier": "فاخر"
  }
];

  window.CAR_BODIES = [
    { key: "Sedan",      ar: "سيدان" },
    { key: "Coupe",      ar: "كوبيه" },
    { key: "SUV",        ar: "دفع رباعي" },
    { key: "Truck",      ar: "شاحنات" },
    { key: "Industrial", ar: "مركبات صناعية" },
    { key: "ATV",        ar: "دراجات رباعية" },
    { key: "Bus",        ar: "حافلات" },
    { key: "Car",        ar: "متنوعة" }
  ];
  